// seed/attendanceName.js
export const collectionName = 'attendanceName';

export const seedData = [
  { name: "Anandan", categoryId: null, dayFee: 900 },
  { name: "Anji", categoryId: null, dayFee: 900 },
  { name: "Ashok", categoryId: null, dayFee: 900 },
  { name: "Kumar", categoryId: null, dayFee: 900 },
  { name: "Kesavan", categoryId: null, dayFee: 900 },
  { name: "Poovarasan", categoryId: null, dayFee: 900 },
  { name: "Prathap", categoryId: null, dayFee: 900 },
  { name: "Sathish", categoryId: null, dayFee: 900 },
  { name: "Seeni", categoryId: null, dayFee: 900 },
  { name: "Shiva", categoryId: null, dayFee: 900 },
  { name: "Suresh", categoryId: null, dayFee: 900 },
  { name: "Mathubalan", categoryId: null, dayFee: 1000 },
  { name: "Muthu", categoryId: null, dayFee: 1000 },
  { name: "Rajendiran", categoryId: null, dayFee: 1000 },
  { name: "Saravanan", categoryId: null, dayFee: 1000 },
  { name: "Sekar", categoryId: null, dayFee: 1000 },
  { name: "Senthil", categoryId: null, dayFee: 1000 },
  { name: "Anbu", categoryId: null, dayFee: 600 },
  { name: "Arasu", categoryId: null, dayFee: 600 },
  { name: "Bangaru ", categoryId: null, dayFee: 600 },
  { name: "Gowtham", categoryId: null, dayFee: 600 },
  { name: "Nandha kumar", categoryId: null, dayFee: 600 },
  { name: "Sridhar", categoryId: null, dayFee: 600 },
  { name: "Balaji", categoryId: null, dayFee: 950 },
  { name: "Kumar", categoryId: null, dayFee: 950 },
  { name: "Murugesan", categoryId: null, dayFee: 950 },
  { name: "Murali", categoryId: null, dayFee: 950 },
  { name: "Govinthan", categoryId: null, dayFee: 800 },
  { name: "Raja", categoryId: null, dayFee: 750 },
  { name: "Dhashinamoorthy", categoryId: null, dayFee: 750 },
  { name: "Sundramoorthy", categoryId: null, dayFee: 750 },
  { name: "Papaiyan", categoryId: null, dayFee: 750 },
  { name: "Ashokan", categoryId: null, dayFee: 750 },
  { name: "Viswanathan", categoryId: null, dayFee: 750 },
  { name: "Ponurangam", categoryId: null, dayFee: 750 },
];
