// seed/cash_description.js
export const collectionName = 'cash_description';

export const seedData = [
  { description: '1/2 Bold', created_at: new Date() },
  { description: '102 Reddiyur', created_at: new Date() },
  { description: '1465 Adblue Oil', created_at: new Date() },
  { description: '1465 Toll Bill', created_at: new Date() },
  { description: '1465 Vehicle', created_at: new Date() },
  { description: '1566 Toll Bill', created_at: new Date() },
  { description: '1566 Vehicle', created_at: new Date() },
  { description: '3111 Toll Bill', created_at: new Date() },
  { description: '3111 Vehicle', created_at: new Date() },
  { description: '3303 Adblue Oil', created_at: new Date() },
  { description: '3303 Toll Bill', created_at: new Date() },
  { description: '3303 Vehicle', created_at: new Date() },
  { description: '3652 Toll Bill', created_at: new Date() },
  { description: '3652 Vehicle', created_at: new Date() },
  { description: '3874 Toll Bill', created_at: new Date() },
  { description: '3874 Vehicle', created_at: new Date() },
  { description: '3879 Vehicle', created_at: new Date() },
  { description: '4844 Vehicle', created_at: new Date() },
  { description: '4971 Vehicle', created_at: new Date() },
  { description: '7277 Toll Bill', created_at: new Date() },
  { description: '7277 Vehicle', created_at: new Date() },
  { description: '7299 Toll Bill', created_at: new Date() },
  { description: '7299 Vehicle', created_at: new Date() },
  { description: '7320 Adblue Oil', created_at: new Date() },
  { description: '7320 Toll Bill', created_at: new Date() },
  { description: '7320 Vehicle', created_at: new Date() },
  { description: '8961 Toll Bill', created_at: new Date() },
  { description: '8961 Vehicle', created_at: new Date() },
  { description: '8982 Toll Bill', created_at: new Date() },
  { description: '8982 Vehicle', created_at: new Date() },
  { description: '9553 Adblue Oil', created_at: new Date() },
  { description: '9553 Toll Bill', created_at: new Date() },
  { description: '9553 Vehicle', created_at: new Date() },
  { description: '9761 Toll Bill', created_at: new Date() },
  { description: '9761 Vehicle', created_at: new Date() },
  { description: 'Anandhan Driver', created_at: new Date() },
  { description: 'Anji Driver', created_at: new Date() },
  { description: 'Arasu Cleaner', created_at: new Date() },
  { description: 'Ashok Driver', created_at: new Date() },
  { description: 'Ashokan Crusher', created_at: new Date() },
  { description: 'Balaji Crusher', created_at: new Date() },
  { description: 'Bangaru Cleaner', created_at: new Date() },
  { description: 'Baskar Opp', created_at: new Date() },
  { description: 'Bend', created_at: new Date() },
  { description: 'Bunk', created_at: new Date() },
  { description: 'Catridge Refill', created_at: new Date() },
  { description: 'Chakka Food', created_at: new Date() },
  { description: 'Chemical Explosive Mayil', created_at: new Date() },
  { description: 'Chemical Explosive VM', created_at: new Date() },
  { description: 'Compresser Air', created_at: new Date() },
  { description: 'Cooldrings', created_at: new Date() },
  { description: 'Crane Fees', created_at: new Date() },
  { description: 'Dakshinamoorthy Crusher', created_at: new Date() },
  { description: 'Drinking Water Cane', created_at: new Date() },
  { description: 'Electrician', created_at: new Date() },
  { description: 'Flower Fees', created_at: new Date() },
  { description: 'Food', created_at: new Date() },
  { description: 'GAS', created_at: new Date() },
  { description: 'Govindharaj Watchman', created_at: new Date() },
  { description: 'Govinthan Crusher', created_at: new Date() },
  { description: 'Govinthan Opp', created_at: new Date() },
  { description: 'Gowtham Cleaner', created_at: new Date() },
  { description: 'Gowtham Opp', created_at: new Date() },
  { description: 'Guna (Acc) Mgr', created_at: new Date() },
  { description: 'Guna (Food) Mgr', created_at: new Date() },
  { description: 'JCB Teeth', created_at: new Date() },
  { description: 'Kesavan Driver', created_at: new Date() },
  { description: 'Krishnamoorthy Driver', created_at: new Date() },
  { description: 'Kumar Crusher', created_at: new Date() },
  { description: 'Kumar Driver', created_at: new Date() },
  { description: 'Rent JCB', created_at: new Date() },
  { description: 'Lokesh Cleaner', created_at: new Date() },
  { description: 'Mani Watchman', created_at: new Date() },
  { description: 'Mathubalan Driver', created_at: new Date() },
  { description: 'Mayil Paarai', created_at: new Date() },
  { description: 'MD’s Advance', created_at: new Date() },
  { description: 'MD’s Drawings', created_at: new Date() },
  { description: 'Mehanic Petrol', created_at: new Date() },
  { description: 'Mogan Parai', created_at: new Date() },
  { description: 'MSS parcel', created_at: new Date() },
  { description: 'Munisamy', created_at: new Date() },
  { description: 'Murali Crusher', created_at: new Date() },
  { description: 'Murugan Driver', created_at: new Date() },
  { description: 'Murugesan Crusher', created_at: new Date() },
  { description: 'Muthu Driver', created_at: new Date() },
  { description: 'Nandha Kumar Cleaner', created_at: new Date() },
  { description: 'Nataraj (Acc) Mgr', created_at: new Date() },
  { description: 'Nut And Bolt', created_at: new Date() },
  { description: 'New Catridge', created_at: new Date() },
  { description: 'Paarai Food', created_at: new Date() },
  { description: 'Palani Welder', created_at: new Date() },
  { description: 'Paneer Crusher', created_at: new Date() },
  { description: 'Paneer Driver', created_at: new Date() },
  { description: 'Papaiyan Crusher', created_at: new Date() },
  { description: 'Paper', created_at: new Date() },
  { description: 'Parai Water', created_at: new Date() },
  { description: 'Party', created_at: new Date() },
  { description: 'Party 909', created_at: new Date() },
  { description: 'Party 912', created_at: new Date() },
  { description: 'Party Advance', created_at: new Date() },
  { description: 'Party Auto', created_at: new Date() },
  { description: 'Party Lorry', created_at: new Date() },
  { description: 'Party T', created_at: new Date() },
  { description: 'Pasim Cleaner', created_at: new Date() },
  { description: 'Petrol', created_at: new Date() },
  { description: 'Police', created_at: new Date() },
  { description: 'Pooja Expense', created_at: new Date() },
  { description: 'Pragasam Driver', created_at: new Date() },
  { description: 'Raja Crusher', created_at: new Date() },
  { description: 'Rajendiran Driver', created_at: new Date() },
  { description: 'Rajesh Opp', created_at: new Date() },
  { description: 'Rent Hitachi', created_at: new Date() },
  { description: 'Samraj Mgr', created_at: new Date() },
  { description: 'Saravanan Driver', created_at: new Date() },
  { description: 'Saravanan (Acc) Mgr', created_at: new Date() },
  { description: 'Saravanan (Food) Mgr', created_at: new Date() },
  { description: 'Sathish Driver', created_at: new Date() },
  { description: 'Seeni Driver', created_at: new Date() },
  { description: 'Seeni (Acc) Mgr', created_at: new Date() },
  { description: 'Seeni (Food) Mgr', created_at: new Date() },
  { description: 'Sekar Driver', created_at: new Date() },
  { description: 'Senthil Driver', created_at: new Date() },
  { description: 'Shiva Driver', created_at: new Date() },
  { description: 'Shiva Mgr', created_at: new Date() },
  { description: 'Singaram Driver', created_at: new Date() },
  { description: 'Stock', created_at: new Date() },
  { description: 'Subramani Watchman', created_at: new Date() },
  { description: 'Sundarmoorthy Crusher', created_at: new Date() },
  { description: 'Suresh Driver', created_at: new Date() },
  { description: 'Swetha Agencies', created_at: new Date() },
  { description: 'TATA Motor', created_at: new Date() },
  { description: 'Tea', created_at: new Date() },
  { description: 'Tirupathy Opp', created_at: new Date() },
  { description: 'Vellore Mechanic', created_at: new Date() },
  { description: 'Vengatajalam (Acc) Mgr', created_at: new Date() },
  { description: 'Vengatajalam (Food) Mgr', created_at: new Date() },
  { description: 'Viji Electrician', created_at: new Date() },
  { description: 'Viswanathan Crusher', created_at: new Date() },
  { description: 'Welding Rod', created_at: new Date() },
  { description: 'Lemon', created_at: new Date() },
  { description: 'JCB 215', created_at: new Date() },
  { description: 'JCB 225 Braker', created_at: new Date() },
  { description: 'JCB 225 Bucketing', created_at: new Date() },
  { description: 'Loader', created_at: new Date() },
  { description: 'Ponnurangam Crusher', created_at: new Date() },
  { description: 'Yoke Set Plate', created_at: new Date() },
  { description: 'Electrical Things', created_at: new Date() },
  { description: 'Ramki (Acc) Mgr', created_at: new Date() },
  { description: 'Ramki (Food) Mgr', created_at: new Date() },
  { description: 'Vellore Shabeer Bhai', created_at: new Date() },
  { description: 'Permit Tirupathur', created_at: new Date() },
  { description: 'Palani Patrai', created_at: new Date() },
  { description: 'Magalingam Crusher', created_at: new Date() },
  { description: 'Kumar Body Fitter', created_at: new Date() },
  { description: 'Granding Machine', created_at: new Date() },
  { description: '0196 Vehicle', created_at: new Date() },
  { description: '0196 AdBlue Oil', created_at: new Date() },
  { description: '0196 Toll Bill', created_at: new Date() },
  { description: 'Thaluk Station', created_at: new Date() },
  { description: 'Trafic Police', created_at: new Date() },
  { description: 'Town Police', created_at: new Date() },
  { description: 'Taluk Police', created_at: new Date() },
  { description: 'Trafic Inspector', created_at: new Date() },
  { description: 'Poovarasan Driver', created_at: new Date() },
  { description: 'Manigandan Cleaner', created_at: new Date() },
  { description: 'Chemical Vehicle Rent', created_at: new Date() },
  { description: 'Donation', created_at: new Date() },
  { description: 'LNV Lorry', created_at: new Date() },
  { description: 'Guna (Bus Fees) Mgr', created_at: new Date() },
  { description: 'Ravi Doser Cleaner', created_at: new Date() },
  { description: 'A1 Parcel', created_at: new Date() },
  { description: 'Vinnamangalam Water', created_at: new Date() },
  { description: 'Workshop', created_at: new Date() },
  { description: 'Tea & Food', created_at: new Date() },
  { description: 'Tiffin', created_at: new Date() },
  { description: 'M Sand Soft Welding', created_at: new Date() },
  { description: 'Paarai EB', created_at: new Date() },
  { description: 'Hospital', created_at: new Date() },
  { description: 'Algm Police', created_at: new Date() },
  { description: 'Taluk Station', created_at: new Date() },
  { description: 'Campresser', created_at: new Date() },
  { description: 'Sub Collector Office', created_at: new Date() },
  { description: '5052 Vehicle', created_at: new Date() },
  { description: '5067 Vehicle', created_at: new Date() },
  { description: '5052 Toll Bill', created_at: new Date() },
  { description: '5067 Toll Bill', created_at: new Date() },
  { description: 'Thindivanam Siva', created_at: new Date() },
];
