// seed/cashDescription.js
export const collectionName = 'cashDescription';

export const seedData = [
  { description: '1/2 Bold', createdAt: new Date() },
  { description: '102 Reddiyur', createdAt: new Date() },
  { description: '1465 Adblue Oil', createdAt: new Date() },
  { description: '1465 Toll Bill', createdAt: new Date() },
  { description: '1465 Vehicle', createdAt: new Date() },
  { description: '1566 Toll Bill', createdAt: new Date() },
  { description: '1566 Vehicle', createdAt: new Date() },
  { description: '3111 Toll Bill', createdAt: new Date() },
  { description: '3111 Vehicle', createdAt: new Date() },
  { description: '3303 Adblue Oil', createdAt: new Date() },
  { description: '3303 Toll Bill', createdAt: new Date() },
  { description: '3303 Vehicle', createdAt: new Date() },
  { description: '3652 Toll Bill', createdAt: new Date() },
  { description: '3652 Vehicle', createdAt: new Date() },
  { description: '3874 Toll Bill', createdAt: new Date() },
  { description: '3874 Vehicle', createdAt: new Date() },
  { description: '3879 Vehicle', createdAt: new Date() },
  { description: '4844 Vehicle', createdAt: new Date() },
  { description: '4971 Vehicle', createdAt: new Date() },
  { description: '7277 Toll Bill', createdAt: new Date() },
  { description: '7277 Vehicle', createdAt: new Date() },
  { description: '7299 Toll Bill', createdAt: new Date() },
  { description: '7299 Vehicle', createdAt: new Date() },
  { description: '7320 Adblue Oil', createdAt: new Date() },
  { description: '7320 Toll Bill', createdAt: new Date() },
  { description: '7320 Vehicle', createdAt: new Date() },
  { description: '8961 Toll Bill', createdAt: new Date() },
  { description: '8961 Vehicle', createdAt: new Date() },
  { description: '8982 Toll Bill', createdAt: new Date() },
  { description: '8982 Vehicle', createdAt: new Date() },
  { description: '9553 Adblue Oil', createdAt: new Date() },
  { description: '9553 Toll Bill', createdAt: new Date() },
  { description: '9553 Vehicle', createdAt: new Date() },
  { description: '9761 Toll Bill', createdAt: new Date() },
  { description: '9761 Vehicle', createdAt: new Date() },
  { description: 'Anandhan Driver', createdAt: new Date() },
  { description: 'Anji Driver', createdAt: new Date() },
  { description: 'Arasu Cleaner', createdAt: new Date() },
  { description: 'Ashok Driver', createdAt: new Date() },
  { description: 'Ashokan Crusher', createdAt: new Date() },
  { description: 'Balaji Crusher', createdAt: new Date() },
  { description: 'Bangaru Cleaner', createdAt: new Date() },
  { description: 'Baskar Opp', createdAt: new Date() },
  { description: 'Bend', createdAt: new Date() },
  { description: 'Bunk', createdAt: new Date() },
  { description: 'Catridge Refill', createdAt: new Date() },
  { description: 'Chakka Food', createdAt: new Date() },
  { description: 'Chemical Explosive Mayil', createdAt: new Date() },
  { description: 'Chemical Explosive VM', createdAt: new Date() },
  { description: 'Compresser Air', createdAt: new Date() },
  { description: 'Cooldrings', createdAt: new Date() },
  { description: 'Crane Fees', createdAt: new Date() },
  { description: 'Dakshinamoorthy Crusher', createdAt: new Date() },
  { description: 'Drinking Water Cane', createdAt: new Date() },
  { description: 'Electrician', createdAt: new Date() },
  { description: 'Flower Fees', createdAt: new Date() },
  { description: 'Food', createdAt: new Date() },
  { description: 'GAS', createdAt: new Date() },
  { description: 'Govindharaj Watchman', createdAt: new Date() },
  { description: 'Govinthan Crusher', createdAt: new Date() },
  { description: 'Govinthan Opp', createdAt: new Date() },
  { description: 'Gowtham Cleaner', createdAt: new Date() },
  { description: 'Gowtham Opp', createdAt: new Date() },
  { description: 'Guna (Acc) Mgr', createdAt: new Date() },
  { description: 'Guna (Food) Mgr', createdAt: new Date() },
  { description: 'JCB Teeth', createdAt: new Date() },
  { description: 'Kesavan Driver', createdAt: new Date() },
  { description: 'Krishnamoorthy Driver', createdAt: new Date() },
  { description: 'Kumar Crusher', createdAt: new Date() },
  { description: 'Kumar Driver', createdAt: new Date() },
  { description: 'Rent JCB', createdAt: new Date() },
  { description: 'Lokesh Cleaner', createdAt: new Date() },
  { description: 'Mani Watchman', createdAt: new Date() },
  { description: 'Mathubalan Driver', createdAt: new Date() },
  { description: 'Mayil Paarai', createdAt: new Date() },
  { description: 'MD’s Advance', createdAt: new Date() },
  { description: 'MD’s Drawings', createdAt: new Date() },
  { description: 'Mehanic Petrol', createdAt: new Date() },
  { description: 'Mogan Parai', createdAt: new Date() },
  { description: 'MSS parcel', createdAt: new Date() },
  { description: 'Munisamy', createdAt: new Date() },
  { description: 'Murali Crusher', createdAt: new Date() },
  { description: 'Murugan Driver', createdAt: new Date() },
  { description: 'Murugesan Crusher', createdAt: new Date() },
  { description: 'Muthu Driver', createdAt: new Date() },
  { description: 'Nandha Kumar Cleaner', createdAt: new Date() },
  { description: 'Nataraj (Acc) Mgr', createdAt: new Date() },
  { description: 'Nut And Bolt', createdAt: new Date() },
  { description: 'New Catridge', createdAt: new Date() },
  { description: 'Paarai Food', createdAt: new Date() },
  { description: 'Palani Welder', createdAt: new Date() },
  { description: 'Paneer Crusher', createdAt: new Date() },
  { description: 'Paneer Driver', createdAt: new Date() },
  { description: 'Papaiyan Crusher', createdAt: new Date() },
  { description: 'Paper', createdAt: new Date() },
  { description: 'Parai Water', createdAt: new Date() },
  { description: 'Party', createdAt: new Date() },
  { description: 'Party 909', createdAt: new Date() },
  { description: 'Party 912', createdAt: new Date() },
  { description: 'Party Advance', createdAt: new Date() },
  { description: 'Party Auto', createdAt: new Date() },
  { description: 'Party Lorry', createdAt: new Date() },
  { description: 'Party T', createdAt: new Date() },
  { description: 'Pasim Cleaner', createdAt: new Date() },
  { description: 'Petrol', createdAt: new Date() },
  { description: 'Police', createdAt: new Date() },
  { description: 'Pooja Expense', createdAt: new Date() },
  { description: 'Pragasam Driver', createdAt: new Date() },
  { description: 'Raja Crusher', createdAt: new Date() },
  { description: 'Rajendiran Driver', createdAt: new Date() },
  { description: 'Rajesh Opp', createdAt: new Date() },
  { description: 'Rent Hitachi', createdAt: new Date() },
  { description: 'Samraj Mgr', createdAt: new Date() },
  { description: 'Saravanan Driver', createdAt: new Date() },
  { description: 'Saravanan (Acc) Mgr', createdAt: new Date() },
  { description: 'Saravanan (Food) Mgr', createdAt: new Date() },
  { description: 'Sathish Driver', createdAt: new Date() },
  { description: 'Seeni Driver', createdAt: new Date() },
  { description: 'Seeni (Acc) Mgr', createdAt: new Date() },
  { description: 'Seeni (Food) Mgr', createdAt: new Date() },
  { description: 'Sekar Driver', createdAt: new Date() },
  { description: 'Senthil Driver', createdAt: new Date() },
  { description: 'Shiva Driver', createdAt: new Date() },
  { description: 'Shiva Mgr', createdAt: new Date() },
  { description: 'Singaram Driver', createdAt: new Date() },
  { description: 'Stock', createdAt: new Date() },
  { description: 'Subramani Watchman', createdAt: new Date() },
  { description: 'Sundarmoorthy Crusher', createdAt: new Date() },
  { description: 'Suresh Driver', createdAt: new Date() },
  { description: 'Swetha Agencies', createdAt: new Date() },
  { description: 'TATA Motor', createdAt: new Date() },
  { description: 'Tea', createdAt: new Date() },
  { description: 'Tirupathy Opp', createdAt: new Date() },
  { description: 'Vellore Mechanic', createdAt: new Date() },
  { description: 'Vengatajalam (Acc) Mgr', createdAt: new Date() },
  { description: 'Vengatajalam (Food) Mgr', createdAt: new Date() },
  { description: 'Viji Electrician', createdAt: new Date() },
  { description: 'Viswanathan Crusher', createdAt: new Date() },
  { description: 'Welding Rod', createdAt: new Date() },
  { description: 'Lemon', createdAt: new Date() },
  { description: 'JCB 215', createdAt: new Date() },
  { description: 'JCB 225 Braker', createdAt: new Date() },
  { description: 'JCB 225 Bucketing', createdAt: new Date() },
  { description: 'Loader', createdAt: new Date() },
  { description: 'Ponnurangam Crusher', createdAt: new Date() },
  { description: 'Yoke Set Plate', createdAt: new Date() },
  { description: 'Electrical Things', createdAt: new Date() },
  { description: 'Ramki (Acc) Mgr', createdAt: new Date() },
  { description: 'Ramki (Food) Mgr', createdAt: new Date() },
  { description: 'Vellore Shabeer Bhai', createdAt: new Date() },
  { description: 'Permit Tirupathur', createdAt: new Date() },
  { description: 'Palani Patrai', createdAt: new Date() },
  { description: 'Magalingam Crusher', createdAt: new Date() },
  { description: 'Kumar Body Fitter', createdAt: new Date() },
  { description: 'Granding Machine', createdAt: new Date() },
  { description: '0196 Vehicle', createdAt: new Date() },
  { description: '0196 AdBlue Oil', createdAt: new Date() },
  { description: '0196 Toll Bill', createdAt: new Date() },
  { description: 'Thaluk Station', createdAt: new Date() },
  { description: 'Trafic Police', createdAt: new Date() },
  { description: 'Town Police', createdAt: new Date() },
  { description: 'Taluk Police', createdAt: new Date() },
  { description: 'Trafic Inspector', createdAt: new Date() },
  { description: 'Poovarasan Driver', createdAt: new Date() },
  { description: 'Manigandan Cleaner', createdAt: new Date() },
  { description: 'Chemical Vehicle Rent', createdAt: new Date() },
  { description: 'Donation', createdAt: new Date() },
  { description: 'LNV Lorry', createdAt: new Date() },
  { description: 'Guna (Bus Fees) Mgr', createdAt: new Date() },
  { description: 'Ravi Doser Cleaner', createdAt: new Date() },
  { description: 'A1 Parcel', createdAt: new Date() },
  { description: 'Vinnamangalam Water', createdAt: new Date() },
  { description: 'Workshop', createdAt: new Date() },
  { description: 'Tea & Food', createdAt: new Date() },
  { description: 'Tiffin', createdAt: new Date() },
  { description: 'M Sand Soft Welding', createdAt: new Date() },
  { description: 'Paarai EB', createdAt: new Date() },
  { description: 'Hospital', createdAt: new Date() },
  { description: 'Algm Police', createdAt: new Date() },
  { description: 'Taluk Station', createdAt: new Date() },
  { description: 'Campresser', createdAt: new Date() },
  { description: 'Sub Collector Office', createdAt: new Date() },
  { description: '5052 Vehicle', createdAt: new Date() },
  { description: '5067 Vehicle', createdAt: new Date() },
  { description: '5052 Toll Bill', createdAt: new Date() },
  { description: '5067 Toll Bill', createdAt: new Date() },
  { description: 'Thindivanam Siva', createdAt: new Date() },
];
