// seed/cash_description.js
export const tableName = 'cash_description';

export const tableSchema = `
CREATE TABLE IF NOT EXISTS cash_description (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
`;

export const seedData = [
  { description: '1/2 Bold' },
  { description: '102 Reddiyur' },
  { description: '1465 Adblue Oil' },
  { description: '1465 Toll Bill' },
  { description: '1465 Vehicle' },
  { description: '1566 Toll Bill' },
  { description: '1566 Vehicle' },
  { description: '3111 Toll Bill' },
  { description: '3111 Vehicle' },
  { description: '3303 Adblue Oil' },
  { description: '3303 Toll Bill' },
  { description: '3303 Vehicle' },
  { description: '3652 Toll Bill' },
  { description: '3652 Vehicle' },
  { description: '3874 Toll Bill' },
  { description: '3874 Vehicle' },
  { description: '3879 Vehicle' },
  { description: '4844 Vehicle' },
  { description: '4971 Vehicle' },
  { description: '7277 Toll Bill' },
  { description: '7277 Vehicle' },
  { description: '7299 Toll Bill' },
  { description: '7299 Vehicle' },
  { description: '7320 Adblue Oil' },
  { description: '7320 Toll Bill' },
  { description: '7320 Vehicle' },
  { description: '8961 Toll Bill' },
  { description: '8961 Vehicle' },
  { description: '8982 Toll Bill' },
  { description: '8982 Vehicle' },
  { description: '9553 Adblue Oil' },
  { description: '9553 Toll Bill' },
  { description: '9553 Vehicle' },
  { description: '9761 Toll Bill' },
  { description: '9761 Vehicle' },
  { description: 'Anandhan Driver' },
  { description: 'Anji Driver' },
  { description: 'Arasu Cleaner' },
  { description: 'Ashok Driver' },
  { description: 'Ashokan Crusher' },
  { description: 'Balaji Crusher' },
  { description: 'Bangaru Cleaner' },
  { description: 'Baskar Opp' },
  { description: 'Bend' },
  { description: 'Bunk' },
  { description: 'Catridge Refill' },
  { description: 'Chakka Food' },
  { description: 'Chemical Explosive Mayil' },
  { description: 'Chemical Explosive VM' },
  { description: 'Compresser Air' },
  { description: 'Cooldrings' },
  { description: 'Crane Fees' },
  { description: 'Dakshinamoorthy Crusher' },
  { description: 'Drinking Water Cane' },
  { description: 'Electrician' },
  { description: 'Flower Fees' },
  { description: 'Food' },
  { description: 'GAS' },
  { description: 'Govindharaj Watchman' },
  { description: 'Govinthan Crusher' },
  { description: 'Govinthan Opp' },
  { description: 'Gowtham Cleaner' },
  { description: 'Gowtham Opp' },
  { description: 'Guna (Acc) Mgr' },
  { description: 'Guna (Food) Mgr' },
  { description: 'JCB Teeth' },
  { description: 'Kesavan Driver' },
  { description: 'Krishnamoorthy Driver' },
  { description: 'Kumar Crusher' },
  { description: 'Kumar Driver' },
  { description: 'Rent JCB' },
  { description: 'Lokesh Cleaner' },
  { description: 'Mani Watchman' },
  { description: 'Mathubalan Driver' },
  { description: 'Mayil Paarai' },
  { description: 'MD’s Advance' },
  { description: 'MD’s Drawings' },
  { description: 'Mehanic Petrol' },
  { description: 'Mogan Parai' },
  { description: 'MSS parcel' },
  { description: 'Munisamy' },
  { description: 'Murali Crusher' },
  { description: 'Murugan Driver' },
  { description: 'Murugesan Crusher' },
  { description: 'Muthu Driver' },
  { description: 'Nandha Kumar Cleaner' },
  { description: 'Nataraj (Acc) Mgr' },
  { description: 'Nut And Bolt' },
  { description: 'New Catridge' },
  { description: 'Paarai Food' },
  { description: 'Palani Welder' },
  { description: 'Paneer Crusher' },
  { description: 'Paneer Driver' },
  { description: 'Papaiyan Crusher' },
  { description: 'Paper' },
  { description: 'Parai Water' },
  { description: 'Party' },
  { description: 'Party 909' },
  { description: 'Party 912' },
  { description: 'Party Advance' },
  { description: 'Party Auto' },
  { description: 'Party Lorry' },
  { description: 'Party T' },
  { description: 'Pasim Cleaner' },
  { description: 'Petrol' },
  { description: 'Police' },
  { description: 'Pooja Expense' },
  { description: 'Pragasam Driver' },
  { description: 'Raja Crusher' },
  { description: 'Rajendiran Driver' },
  { description: 'Rajesh Opp' },
  { description: 'Rent Hitachi' },
  { description: 'Samraj Mgr' },
  { description: 'Saravanan Driver' },
  { description: 'Saravanan (Acc) Mgr' },
  { description: 'Saravanan (Food) Mgr' },
  { description: 'Sathish Driver' },
  { description: 'Seeni Driver' },
  { description: 'Seeni (Acc) Mgr' },
  { description: 'Seeni (Food) Mgr' },
  { description: 'Sekar Driver' },
  { description: 'Senthil Driver' },
  { description: 'Shiva Driver' },
  { description: 'Shiva Mgr' },
  { description: 'Singaram Driver' },
  { description: 'Stock' },
  { description: 'Subramani Watchman' },
  { description: 'Sundarmoorthy Crusher' },
  { description: 'Suresh Driver' },
  { description: 'Swetha Agencies' },
  { description: 'TATA Motor' },
  { description: 'Tea' },
  { description: 'Tirupathy Opp' },
  { description: 'Vellore Mechanic' },
  { description: 'Velmani Driver' },
  { description: 'Vengatajalam (Acc) Mgr' },
  { description: 'Vengatajalam (Food) Mgr' },
  { description: 'Viji Electrician' },
  { description: 'Viswanathan Crusher' },
  { description: 'Welding Rod' },
  { description: 'Lemon' },
  { description: 'JCB 215' },
  { description: 'JCB 225 Braker' },
  { description: 'JCB 225 Bucketing' },
  { description: 'Loader' },
  { description: 'Ponnurangam Crusher' },
  { description: 'Yoke Set Plate' },
  { description: 'Electrical Things' },
  { description: 'Ramki (Acc) Mgr' },
  { description: 'Ramki (Food) Mgr' },
  { description: 'Vellore Shabeer Bhai' },
  { description: 'Permit Tirupathur' },
  { description: 'Palani Patrai' },
  { description: 'Magalingam Crusher' },
  { description: 'Kumar Body Fitter' },
  { description: 'Granding Machine' },
  { description: '0196 Vehicle' },
  { description: '0196 AdBlue Oil' },
  { description: '0196 Toll Bill' },
  { description: 'Thaluk Station' },
  { description: 'Trafic Police' },
  { description: 'Town Police' },
  { description: 'Taluk Police' },
  { description: 'Trafic Inspector' },
  { description: 'Poovarasan Driver' },
  { description: 'Manigandan Cleaner' },
  { description: 'Chemical Vehicle Rent' },
  { description: 'Donation' },
  { description: 'LNV Lorry' },
  { description: 'Guna (Bus Fees) Mgr' },
  { description: 'Ravi Doser Cleaner' },
  { description: 'A1 Parcel' },
  { description: 'Vinnamangalam Water' },
  { description: 'Workshop' },
  { description: 'Tea & Food' },
  { description: 'Tiffin' },
  { description: 'M Sand Soft Welding' },
  { description: 'Paarai EB' },
  { description: 'Hospital' },
  { description: 'Algm Police' },
  { description: 'Taluk Station' },
  { description: 'Campresser' },
  { description: 'Sub Collector Office' },
  { description: '5052 Vehicle' },
  { description: '5067 Vehicle' },
  { description: '5052 Toll Bill' },
  { description: '5067 Toll Bill' },
  { description: 'Thindivanam Siva' },
];
