// seed/delivery.js
export const tableName = 'cash_description';

export const tableSchema = `
CREATE TABLE IF NOT EXISTS cash_description (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
`;

export const seedData = [
  { description: '1/2 Bold' },
  { description: '102 Reddiyur' },
  { description: '1465 Adblue Oil' },
  { description: '1465 Toll Bill' },
  { description: '1465 Vehicle' },
  { description: '1566 Toll Bill' },
  { description: '1566 Vehicle' },
  { description: '3111 Toll Bill' },
  { description: '3111 Vehicle' },
  { description: '3303 Adblue Oil' },
  { description: '3303 Toll Bill' },
  { description: '3303 Vehicle' },
  { description: '3652 Toll Bill' },
  { description: '3652 Vehicle' },
  { description: '3874 Toll Bill' },
  { description: '3874 Vehicle' },
  { description: '3879 Vehicle' },
  { description: '4844 Vehicle' },
  { description: '4971 Vehicle' },
  { description: '7277 Toll Bill' },
  { description: '7277 Vehicle' },
  { description: '7299 Toll Bill' },
  { description: '7299 Vehicle' },
  { description: '7320 Adblue Oil' },
  { description: '7320 Toll Bill' },
  { description: '7320 Vehicle' },
  { description: '8961 Toll Bill' },
  { description: '8961 Vehicle' },
  { description: '8982 Toll Bill' },
  { description: '8982 Vehicle' },
  { description: '9553 Adblue Oil' },
  { description: '9553 Toll Bill' },
  { description: '9553 Vehicle' },
  { description: '9761 Toll Bill' },
  { description: '9761 Vehicle' },
  { description: 'A1 City' },
  { description: 'ADS' },
  { description: 'ADS driver murugan O/B' },
  { description: 'ADS O/B' },
  { description: 'AGS' },
  { description: 'AGS Construction O/B' },
  { description: 'Akbar Kousil O/B' },
  { description: 'Alangayam' },
  { description: 'Alasanthapuram' },
  { description: 'Ambalur' },
  { description: 'Ambur pettai' },
  { description: 'Anandhan Auditor O/B' },
  { description: 'Anandhan Driver' },
  { description: 'Anbu Alangayam O/B' },
  { description: 'Andiyappanur' },
  { description: 'Anji Driver' },
  { description: 'Annamalayar Lorry' },
  { description: 'Annamalayar Lorry O/B' },
  { description: 'Annasamy' },
  { description: 'Annasamy Lorry' },
  { description: 'Annasamy Lorry O/B' },
  { description: 'APN' },
  { description: 'Apollo Traders O/B' },
  { description: 'Arasu Cleaner' },
  { description: 'Aravindhan VNM' },
  { description: 'Armanibenta' },
  { description: 'Asanampattu' },
  { description: 'Ashok Driver' },
  { description: 'Ashokan Crusher' },
  { description: 'Asif Bhai O/B' },
  { description: 'Avaranguppam' },
  { description: 'AVR' },
  { description: 'AVR Lorry O/B' },
  { description: 'Babu Mesthiri O/B' },
  { description: 'Bakirthaka' },
  { description: 'Balaji Crusher' },
  { description: 'Bangaru Cleaner' },
  { description: 'Bankoor' },
  { description: 'Basheerabad' },
  { description: 'Baskar Opp' },
  { description: 'Bath Auto O/B' },
  { description: 'Bend' },
  { description: 'Bethavepampattu' },
  { description: 'Bethur' },
  { description: 'BK mani' },
  { description: 'BK mani O/B' },
  { description: 'BKB LORRY' },
  { description: 'Bunk' },
  { description: 'Catridge Refill' },
  { description: 'Chakka Food' },
  { description: 'Chekumedu' },
  { description: 'Chemical Explosive Mayil' },
  { description: 'Chemical Explosive VM' },
  { description: 'Chikanankuppam' },
  { description: 'Chinnakalupalli' },
  { description: 'Chinnamottur' },
  { description: 'College Principal O/B' },
  { description: 'Compresser Air' },
  { description: 'Cooldrings' },
  { description: 'Crane Fees' },
  { description: 'CV patrai' },
  { description: 'Dakshinamoorthy Crusher' },
  { description: 'DKP Lorry' },
  { description: 'DR' },
  { description: 'DR lorry O/B' },
  { description: 'Drinking Water Cane' },
  { description: 'Echangal' },
  { description: 'Eklaspuram' },
  { description: 'Elavarasan O/B' },
  { description: 'Electrician' },
  { description: 'Eniyavan Auto O/B' },
  { description: 'Ezhalaraipatti' },
  { description: 'Flower Fees' },
  { description: 'Food' },
  { description: 'Forest Office O/B' },
  { description: 'Ganesh Babu O/B' },
  { description: 'Ganesh Tracktor' },
  { description: 'GAS' },
  { description: 'Giri samuthiram' },
  { description: 'Goundappanur' },
  { description: 'Govindharaj Watchman' },
  { description: 'Govinthan Crusher' },
  { description: 'Govinthan Opp' },
  { description: 'Gowtham Cleaner' },
  { description: 'Gowtham Opp' },
  { description: 'GSK' },
  { description: 'GSK Manager O/B' },
  { description: 'GSK O/B' },
  { description: 'Guna Manager O/B' },
  { description: 'Guna (Acc) Mgr' },
  { description: 'Guna (Food) Mgr' },
  { description: 'GVM' },
  { description: 'GVM lorry O/B' },
  { description: 'Hari Ohm Balaji Lorry' },
  { description: 'Idayampallam' },
  { description: 'Ikbal Road Majid O/B' },
  { description: 'Ilayanagaram' },
  { description: 'Indra Nagar' },
  { description: 'Irshad Bhai O/B' },
  { description: 'Irunapattu' },
  { description: 'Islamiah Boys College O/B' },
  { description: 'Islamiah School O/B' },
  { description: 'Jabrabad' },
  { description: 'Jagadisan Thalaivar O/B' },
  { description: 'Jamal Bhai O/B' },
  { description: 'Jamunamathur' },
  { description: 'Janathapuram' },
  { description: 'JCB Teeth' },
  { description: 'JKT' },
  { description: 'JNS Lorry' },
  { description: 'Jolarpet' },
  { description: 'JPP' },
  { description: 'JPP O/B' },
  { description: 'Juber bhai O/B' },
  { description: 'Kaburabad' },
  { description: 'Kadharpet' },
  { description: 'Kalendira' },
  { description: 'Kallupalli' },
  { description: 'Kalrapatti' },
  { description: 'Kamal Kuttai' },
  { description: 'Kambangudi Malai' },
  { description: 'Kanavaipudhur' },
  { description: 'Kandavel Trackter O/B' },
  { description: 'Karimabad' },
  { description: 'Katteri' },
  { description: 'Kavalur' },
  { description: 'Kaveripattu' },
  { description: 'Kavi soap O/B' },
  { description: 'Kesavan Driver' },
  { description: 'Kethanndapaatti' },
  { description: 'Kizhulur' },
  { description: 'KK Kottai' },
  { description: 'KK Theru' },
  { description: 'Kodiyoor (Konambatti)' },
  { description: 'Konnampatti' },
  { description: 'Kootroad' },
  { description: 'Kooval Kuttai' },
  { description: 'Krishna Lorry O/B' },
  { description: 'Krishnamoorthy Driver' },
  { description: 'Krishnamoorthy Mayilparai O/B' },
  { description: 'Krishnamoorthy Mesthiri O/B' },
  { description: 'Krishnavaram' },
  { description: 'Kumar Crusher' },
  { description: 'Kumar Driver' },
  { description: 'Kumar Driver Kurumbati O/B' },
  { description: 'Kumarn Mehanic O/B' },
  { description: 'Kunnathur' },
  { description: 'Kurisilapattu' },
  { description: 'Kurumbatheru' },
  { description: 'Kurumpatti' },
  { description: 'KVS Lorry' },
  { description: 'Lakshmipuram' },
  { description: 'Lalayeri' },
  { description: 'Lalayeri Water' },
  { description: 'Rent JCB' },
  { description: 'Lokesh Cleaner' },
  { description: 'LSK yelagiri O/B' },
  { description: 'MA Lorry' },
  { description: 'Madanancheri' },
  { description: 'Madapalli' },
  { description: 'Madavalam' },
  { description: 'Malai Rediyor' },
  { description: 'Mallakuppam' },
  { description: 'Mandalavadi' },
  { description: 'Mani Meson O/B' },
  { description: 'Mani Watchman' },
  { description: 'Manigandan VAO RMS pudur O/B' },
  { description: 'Marapattu HB O/B' },
  { description: 'Marimani kuppam' },
  { description: 'Mathubalan Driver' },
  { description: 'Mayil Paarai' },
  { description: 'MBS Lorry' },
  { description: 'MD’s Advance' },
  { description: 'MD’s Drawings' },
  { description: 'Mehanic Petrol' },
  { description: 'Mel Nimmiyampattu' },
  { description: 'Mel Nimmiyampattu Party O/B' },
  { description: 'Metupalayam' },
  { description: 'Mittur' },
  { description: 'MKB Lorry' },
  { description: 'MKR' },
  { description: 'MKR O/B' },
  { description: 'Mogan Parai' },
  { description: 'Moorthi Jamunamathur O/B' },
  { description: 'MPM Lorrry' },
  { description: 'MRT Lorry' },
  { description: 'MSS Lorry' },
  { description: 'MSS parcel' },
  { description: 'Mukthiyar Bhai O/B' },
  { description: 'Mullai' },
  { description: 'Mullai Bunk, Marapattu O/B' },
  { description: 'Munisamy' },
  { description: 'Munivel Poongulam O/B' },
  { description: 'Murali Crusher' },
  { description: 'Murugan Driver' },
  { description: 'Murugesan Crusher' },
  { description: 'Murugesan Tractor' },
  { description: 'Muthu Driver' },
  { description: 'Nakkunthi' },
  { description: 'Nandha Kumar Cleaner' },
  { description: 'Naneri' },
  { description: 'Narasingapuram' },
  { description: 'Narayana Mesthiri O/B' },
  { description: 'Narayanapuram' },
  { description: 'Nashir Bhai O/B' },
  { description: 'Nataraj (Acc) Mgr' },
  { description: 'Natrampalli' },
  { description: 'Naveed Traders O/B' },
  { description: 'Nawaz Bhai O/B' },
  { description: 'Nut And Bolt' },
  { description: 'Nethaji Nagar' },
  { description: 'New Catridge' },
  { description: 'Newtown' },
  { description: 'Nimmiyampattu' },
  { description: 'NS & CO' },
  { description: 'Old Vaniyambadi' },
  { description: 'Omakuppam' },
  { description: 'Paapaneri' },
  { description: 'Paarai Food' },
  { description: 'Palani Welder' },
  { description: 'Palanimurugan Lorry' },
  { description: 'Pallipattu' },
  { description: 'Paneer Crusher' },
  { description: 'Paneer Driver' },
  { description: 'Papaiyan Crusher' },
  { description: 'Papanoor Medu' },
  { description: 'Paper' },
  { description: 'Parai Water' },
  { description: 'Parthiban Lorry' },
  { description: 'Parthiban Lorry O/B' },
  { description: 'Party' },
  { description: 'Party 909' },
  { description: 'Party 912' },
  { description: 'Party Advance' },
  { description: 'Party Auto' },
  { description: 'Party Lorry' },
  { description: 'Party T' },
  { description: 'Pasalikuttai' },
  { description: 'Pasim Cleaner' },
  { description: 'Pattabi O/B' },
  { description: 'Pernampattu' },
  { description: 'Perumal Cement' },
  { description: 'Perumalpettai' },
  { description: 'Perumapattu' },
  { description: 'Petrol' },
  { description: 'PKP' },
  { description: 'PMC' },
  { description: 'PMC lorry O/B' },
  { description: 'Police' },
  { description: 'Ponneri' },
  { description: 'Pooja Expense' },
  { description: 'Poomaram' },
  { description: 'Poongulam' },
  { description: 'Pragasam Driver' },
  { description: 'Pudhur VNB' },
  { description: 'Pudupettai' },
  { description: 'Pudurnadu' },
  { description: 'Pullakuttai' },
  { description: 'Puthukovil' },
  { description: 'Ragavendra Electrical O/B' },
  { description: 'Raja Crusher' },
  { description: 'Rajendiran Driver' },
  { description: 'Rajesh Opp' },
  { description: 'Ramanayakanpettai' },
  { description: 'Ranipettai' },
  { description: 'Reddyvalasai' },
  { description: 'Rent Hitachi' },
  { description: 'RMS Pudur' },
  { description: 'Samraj Mgr' },
  { description: 'Sarathi VNB O/B' },
  { description: 'Saravana Cement O/B' },
  { description: 'Saravanan Driver' },
  { description: 'Saravanan Manager O/B' },
  { description: 'Saravanan Mesthiri O/B' },
  { description: 'Saravanan (Acc) Mgr' },
  { description: 'Saravanan (Food) Mgr' },
  { description: 'Sathiram' },
  { description: 'Sathish Driver' },
  { description: 'Sathyam Construction O/B' },
  { description: 'SDK' },
  { description: 'SDK O/B' },
  { description: 'Seeni Driver' },
  { description: 'Seeni (Acc) Mgr' },
  { description: 'Seeni (Food) Mgr' },
  { description: 'Seenivasan Eng O/B' },
  { description: 'Sekar Driver' },
  { description: 'Sekar Mesthiri O/B' },
  { description: 'Sennampettai' },
  { description: 'Senthil Driver' },
  { description: 'Shakil Bhai O/B' },
  { description: 'Shakirabad' },
  { description: 'Shiva Driver' },
  { description: 'Shiva Mgr' },
  { description: 'Shiva T O/B' },
  { description: 'Shivaji Theater  O/B' },
  { description: 'Singaram Driver' },
  { description: 'Sivakumar P O/B' },
  { description: 'SMLS Lorry' },
  { description: 'SMT Lorry' },
  { description: 'Sokkalingam RI O/B' },
  { description: 'Sorkalnatham' },
  { description: 'SRS Lorry' },
  { description: 'SSS' },
  { description: 'SSS Construction O/B' },
  { description: 'Stock' },
  { description: 'Subramani Driver (GSK) O/B' },
  { description: 'Subramani Watchman' },
  { description: 'Sugarmill' },
  { description: 'Sundarmoorthy Crusher' },
  { description: 'Sunnambu Pallam' },
  { description: 'Suresh Auto Driver Gpay O/B' },
  { description: 'Suresh Driver' },
  { description: 'Swetha Agencies' },
  { description: 'TATA Motor' },
  { description: 'Tea' },
  { description: 'Thimanur' },
  { description: 'Thimanur HB O/B' },
  { description: 'Thimmampettai' },
  { description: 'Thiriyalam' },
  { description: 'Thulasi Mesthiri O/B' },
  { description: 'Thumberi' },
  { description: 'Tirupathur' },
  { description: 'Tirupathy Opp' },
  { description: 'TLG' },
  { description: 'TLG O/B' },
  { description: 'Utham CL road O/B' },
  { description: 'Utheynthiram' },
  { description: 'Vadacheri' },
  { description: 'Vadakkupattu' },
  { description: 'Valayampattu' },
  { description: 'Vallipattu' },
  { description: 'Vanitech O/B' },
  { description: 'Vaniyambadi' },
  { description: 'Velathigamanibenta' },
  { description: 'Vellakkal' },
  { description: 'Vellakuttai' },
  { description: 'Vellore Mechanic' },
  { description: 'Velmani Driver' },
  { description: 'Velmani Driver O/B' },
  { description: 'Vengalapuram' },
  { description: 'Vengatajalam (Acc) Mgr' },
  { description: 'Vengatajalam (Food) Mgr' },
  { description: 'Vengayapalli' },
  { description: 'Vepalampatti' },
  { description: 'Vepamarasalai' },
  { description: 'Vepamatta yeri' },
  { description: 'Veppampattu' },
  { description: 'Vijay Medical O/B' },
  { description: 'Viji Electrician' },
  { description: 'Vijilapuram' },
  { description: 'Viswanathan Crusher' },
  { description: 'VNK Advance' },
  { description: 'VNK Lorry' },
  { description: 'VRM' },
  { description: 'VRM O/B' },
  { description: 'VSL' },
  { description: 'VSL HB O/B' },
  { description: 'Welding Rod' },
  { description: 'Yalini Traders' },
  { description: 'Yalini Traders O/B' },
  { description: 'Yelagiri' },
  { description: 'Lemon' },
  { description: 'ChennamPettai' },
  { description: 'Patha Pettai' },
  { description: 'JCB 215' },
  { description: 'JCB 225 Braker' },
  { description: 'JCB 225 Bucketing' },
  { description: 'Loader' },
  { description: 'Ponnurangam Crusher' },
  { description: 'Pulavar Palli' },
  { description: 'Chettiyappanur' },
  { description: 'Yoke Set Plate' },
  { description: 'Electrical Things' },
  { description: 'Pachur' },
  { description: 'Venkatarajapuram' },
  { description: 'Balapanur' },
  { description: 'ThekkuPattu' },
  { description: 'Lakshmi Store O/B' },
  { description: 'Kalam School' },
  { description: 'SankaraPuram' },
  { description: 'Ramki (Acc) Mgr' },
  { description: 'Ramki (Food) Mgr' },
  { description: 'SPT Lorry' },
  { description: 'Kodayanji' },
  { description: 'Vellore Shabeer Bhai' },
  { description: 'Permit Tirupathur' },
  { description: 'Palani Patrai' },
  { description: 'Mitnanguppam' },
  { description: 'Mallagunda' },
  { description: 'Periyapettai' },
  { description: 'Magalingam Crusher' },
  { description: 'VM Explosive Vehicle' },
  { description: 'Vengatarajapuram' },
  { description: 'Thamanerimuthur' },
  { description: 'GSK Kumar' },
  { description: 'CSK' },
  { description: 'Thimanur HB' },
  { description: 'Gunreddyor' },
  { description: 'Konamedu' },
  { description: 'Kumaran Lorry' },
  { description: 'LMK Lorry' },
  { description: 'Kammiyampattu' },
  { description: 'Mandharakuttai' },
  { description: 'AVM Lorry' },
  { description: '0196 Vehicle' },
  { description: 'Kumar Body Fillter' },
  { description: 'Kacheri Road' },
  { description: 'RMD Lorry' },
  { description: 'Ramesh Tracktor' },
  { description: 'Granding Machine' },
  { description: '0196 Vehicle' },
  { description: '0196 AdBlue Oil' },
  { description: '0196 Toll Bill' },
  { description: 'Jalthi' },
  { description: 'Thaluk Station' },
  { description: 'Trafic Police' },
  { description: 'Town Police' },
  { description: 'Taluk Police' },
  { description: 'Trafic Inspector' },
  { description: 'KVS Lorry O/B' },
  { description: 'Mankamarathupallam' },
  { description: 'Naveen Lodge' },
  { description: 'Poovarasan Driver' },
  { description: 'Vinkatarajapuram' },
  { description: 'SJV LORRY' },
  { description: 'Samanthi Kuppam' },
  { description: 'Manigandan Cleaner' },
  { description: 'Chemical Vehicle Rent' },
  { description: 'Donation' },
  { description: 'LNV Lorry' },
  { description: 'College Hostal O/B' },
  { description: 'Guna (Bus Fees) Mgr' },
  { description: 'GSV Lorry' },
  { description: 'GKI Lorry' },
  { description: 'Ravi Doser Cleaner' },
  { description: 'A1 Parcel' },
  { description: 'Vinnamangalam Water' },
  { description: 'Workshop' },
  { description: 'SSK T' },
  { description: 'ANU Lorry' },
  { description: 'Tea&Food' },
  { description: 'RKV Lorry' },
  { description: 'Jambupallam' },
  { description: 'CRM' },
  { description: 'PS Lorry' },
  { description: 'AKR Parcel' },
  { description: 'VVA Lorry' },
  { description: 'Tiffin' },
  { description: 'Alangayam(Pudhur)' },
  { description: 'Akshaya Motor' },
  { description: 'M Sand Soft Welding' },
  { description: 'MRK Lorry' },
  { description: 'Paarai EB' },
  { description: 'Hospital' },
  { description: 'ADD Lorry' },
  { description: 'Arumugam JCB Lorry' },
  { description: 'Algm Police' },
  { description: 'SVM Lorry' },
  { description: 'SRM Lorry' },
  { description: 'Eniyavan Auto' },
  { description: 'Sivakumar Lorry' },
  { description: 'Taluk Station' },
  { description: 'MR Steel' },
  { description: 'Campresser' },
  { description: 'Sub Collector Office' },
  { description: '5052 Vehicle' },
  { description: '5067 Vehicle' },
  { description: '5052 Toll Bill' },
  { description: '5067 Toll Bill' },
  { description: 'Thindivanam Siva' },
  { description: 'ATA Lorry' },
  { description: 'Karthick Lorry' }
];
