// seed/party.js
export const collectionName = 'party';

// Define indexes for better query performance
export const indexes = [
  { spec: { name: 1 }, options: { unique: false } }, // Index on party name (not unique since names might repeat)
  { spec: { phone: 1 } }, // Index for searching by phone number
  { spec: { created_at: -1 } }, // Index for sorting by creation date
  { spec: { name: 1, phone: 1 } }, // Compound index for name + phone searches
];

// Optional: Define MongoDB schema validation
export const validationRules = {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['name'],
      properties: {
        name: {
          bsonType: 'string',
          description: 'must be a string and is required',
        },
        phone: {
          bsonType: ['string', 'null'],
          description: 'must be a string or null',
        },
        opening_balance: {
          bsonType: 'double',
          minimum: 0,
          description: 'must be a positive number',
        },
        created_at: {
          bsonType: ['date', 'null'],
          description: 'must be a date or null',
        },
      },
    },
  },
  level: 'strict',
  action: 'error',
};

// Seed data - converted from SQL format to MongoDB document format
export const seedData = [
  { name: 'ADS', phone: '9790029726', opening_balance: 0.0, created_at: new Date() },
  { name: 'AGS', phone: '9894217717', opening_balance: 0.0, created_at: new Date() },
  { name: 'Akbar Kousar', phone: '9751066446', opening_balance: 0.0, created_at: new Date() },
  { name: 'Amir Bhai', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Anandhan Auditor', phone: '8489855689', opening_balance: 0.0, created_at: new Date() },
  { name: 'Anbu Alangayam', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Annamalayar Lorry', phone: '9443348605', opening_balance: 0.0, created_at: new Date() },
  { name: 'Annasamy Lorry', phone: '9626803399', opening_balance: 0.0, created_at: new Date() },
  { name: 'ANU Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'APN', phone: '9655408325', opening_balance: 0.0, created_at: new Date() },
  { name: 'Apollo Traders', phone: '9443492925', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ashokan Jabrabath', phone: '7845651972', opening_balance: 0.0, created_at: new Date() },
  { name: 'Asif Bhai', phone: '9842325213', opening_balance: 0.0, created_at: new Date() },
  { name: 'ATA', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'AVM Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'AVR Lorry', phone: '8098821310', opening_balance: 0.0, created_at: new Date() },
  { name: 'Babu Auto', phone: '9003810729', opening_balance: 0.0, created_at: new Date() },
  { name: 'Babu Mesthiri', phone: '9443872492', opening_balance: 0.0, created_at: new Date() },
  { name: 'Bangaru Cleaner', phone: '9442744676', opening_balance: 0.0, created_at: new Date() },
  { name: 'Bangaru Driver', phone: '9442744676', opening_balance: 0.0, created_at: new Date() },
  { name: 'Bath Auto', phone: '9003810729', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Bethapalliyamman Kovil',
    phone: '9943310139',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'BK Mani', phone: '9698869671', opening_balance: 0.0, created_at: new Date() },
  { name: 'BKB Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'BKP Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'College Hostal', phone: '9894150004', opening_balance: 0.0, created_at: new Date() },
  { name: 'College Principal', phone: '9486528846', opening_balance: 0.0, created_at: new Date() },
  { name: 'CSK', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Dhashnamoorthy', phone: '9159654756', opening_balance: 0.0, created_at: new Date() },
  { name: 'DKP Lorry', phone: '9789451911', opening_balance: 0.0, created_at: new Date() },
  { name: 'DR Lorry', phone: '9786339076', opening_balance: 0.0, created_at: new Date() },
  { name: 'DRS Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Elavarasan', phone: '9943644105', opening_balance: 0.0, created_at: new Date() },
  { name: 'Emrold Leather', phone: '9443353551', opening_balance: 0.0, created_at: new Date() },
  { name: 'Eniyavan Auto', phone: '9843719307', opening_balance: 0.0, created_at: new Date() },
  { name: 'Forest Babu', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Forest Office', phone: '9443541922', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ganesh Babu', phone: '8939908357', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ganesh Tracktor', phone: '8072258461', opening_balance: 0.0, created_at: new Date() },
  { name: 'GBR Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Gokul Motors', phone: '8072946034', opening_balance: 0.0, created_at: new Date() },
  { name: 'Gopal Lorry', phone: '9790001768', opening_balance: 0.0, created_at: new Date() },
  { name: 'GSK', phone: '9003370713', opening_balance: 0.0, created_at: new Date() },
  { name: 'GSK Kumar', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'GSK Manager', phone: '9047469066', opening_balance: 0.0, created_at: new Date() },
  { name: 'Guna Manager', phone: '8489614965', opening_balance: 0.0, created_at: new Date() },
  { name: 'GVM Lorry', phone: '9943657909', opening_balance: 0.0, created_at: new Date() },
  { name: 'Hari Ohm Balaji Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Herbal Garden', phone: '9943156731', opening_balance: 0.0, created_at: new Date() },
  { name: 'HM Rafiq', phone: '9443490952', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ikbal Road Majid', phone: '9790306797', opening_balance: 0.0, created_at: new Date() },
  { name: 'Irshad Bhai', phone: '9443390157', opening_balance: 0.0, created_at: new Date() },
  { name: 'Islamiah College', phone: '9894150004', opening_balance: 0.0, created_at: new Date() },
  { name: 'Islamiah School', phone: '9894958145', opening_balance: 0.0, created_at: new Date() },
  { name: 'Jagadisan', phone: '9751545991', opening_balance: 0.0, created_at: new Date() },
  { name: 'Jamal Bhai', phone: '8220544004', opening_balance: 0.0, created_at: new Date() },
  { name: 'Janatha Patrai', phone: '9500919724', opening_balance: 0.0, created_at: new Date() },
  { name: 'JKT', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'JNS', phone: '9443091305', opening_balance: 0.0, created_at: new Date() },
  { name: 'JNS Lorry', phone: '9443091305', opening_balance: 0.0, created_at: new Date() },
  { name: 'JPP', phone: '9787852862', opening_balance: 0.0, created_at: new Date() },
  { name: 'Juber Bhai', phone: '8925393141', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kalam School', phone: '9043344080', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kanagarj Mesthiri', phone: '9943924269', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kandavel Trackter', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kavi Soap', phone: '8220162433', opening_balance: 0.0, created_at: new Date() },
  { name: 'KBR', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'KBR Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'KK Shoes', phone: '9597300488', opening_balance: 0.0, created_at: new Date() },
  { name: 'Krishna Lorry', phone: '9003875894', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Krishnamoorthy Mayilparai',
    phone: '9843172296',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  {
    name: 'Krishnamoorthy Mesthiri',
    phone: '9751436645',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'KSM Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kumar Driving School', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Kumaran Lorry', phone: '8110011838', opening_balance: 0.0, created_at: new Date() },
  { name: 'KVS Lorry', phone: '9080851773', opening_balance: 0.0, created_at: new Date() },
  { name: 'Lakshmi Store', phone: '9443882405', opening_balance: 0.0, created_at: new Date() },
  { name: 'LMK Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'LNV Lorry', phone: '9786044807', opening_balance: 0.0, created_at: new Date() },
  { name: 'LSK Yelagiri', phone: '9789395555', opening_balance: 0.0, created_at: new Date() },
  { name: 'LSS Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'MA Lorry', phone: '9787471898', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mani Mesan', phone: '9787461683', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mani Meson', phone: '9585713174', opening_balance: 0.0, created_at: new Date() },
  { name: 'Manigandan Pudur', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mano Vellakuttai', phone: '9943626069', opening_balance: 0.0, created_at: new Date() },
  { name: 'Marapattu HB', phone: '9677790437', opening_balance: 0.0, created_at: new Date() },
  { name: 'Maruthamalai', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'MBS Lorry', phone: '9944090662', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mel Nimmiyampattu Party', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'MKB Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'MKR', phone: '9626076801', opening_balance: 0.0, created_at: new Date() },
  { name: 'MKR Mahendiran', phone: '9600806696', opening_balance: 0.0, created_at: new Date() },
  { name: 'MKR Rajendiran', phone: '9894785661', opening_balance: 0.0, created_at: new Date() },
  { name: 'MLS Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'MLS Lorry, Mullai', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mohan Mosic', phone: '', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Moorthi Jamunamathur',
    phone: '9751555945',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Moorthy JPT', phone: '9789602547', opening_balance: 0.0, created_at: new Date() },
  { name: 'MPM Lorry', phone: '9843352185', opening_balance: 0.0, created_at: new Date() },
  { name: 'MRT Lorry', phone: '8098978696', opening_balance: 0.0, created_at: new Date() },
  { name: 'MSS Lorry', phone: '9943676089', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mukthiyar Bhai', phone: '9994178380', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mullai Bunk, Marapattu', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Munisamy', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Munivel Poongulam', phone: '6380423002', opening_balance: 0.0, created_at: new Date() },
  { name: 'Murugan', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Murugesan Tractor', phone: '6369756856', opening_balance: 0.0, created_at: new Date() },
  { name: 'Narayana Mesthiri', phone: '9626919356', opening_balance: 0.0, created_at: new Date() },
  { name: 'Nashir Bhai', phone: '7010090516', opening_balance: 0.0, created_at: new Date() },
  { name: 'Naveed Traders', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Naveen Spare Parts', phone: '9655867032', opening_balance: 0.0, created_at: new Date() },
  { name: 'Nawaz Bhai', phone: '9543392196', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ns & Co', phone: '9443687211', opening_balance: 0.0, created_at: new Date() },
  { name: 'NSH Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'O Mohanraj School', phone: '8825596789', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Ohm Muruga Construction',
    phone: '7904820993',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Palani Mesthiri', phone: '8754179172', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Palanimurugan Lorry',
    phone: '8870100327',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Parthiban Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Party', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Party 909', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Party 912', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Party Auto', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Party T', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Pattabi', phone: '9025088855', opening_balance: 0.0, created_at: new Date() },
  { name: 'PBJ Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Periyapettai Iyer', phone: '9743955052', opening_balance: 0.0, created_at: new Date() },
  { name: 'PKP', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'PMC Lorry', phone: '9902564857', opening_balance: 0.0, created_at: new Date() },
  { name: 'PMS', phone: '9786715459', opening_balance: 0.0, created_at: new Date() },
  { name: 'Prime Engineers', phone: '9952942812', opening_balance: 0.0, created_at: new Date() },
  { name: 'PRR', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ragavendra Electrical', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Ramesh Tracktor', phone: '9943673865', opening_balance: 0.0, created_at: new Date() },
  { name: 'RKS', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'RMD Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sai Construction', phone: '9943872300', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sankar Konnampatti', phone: '9150652961', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sarathi VNB', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Saravana Cement', phone: '9751845554', opening_balance: 0.0, created_at: new Date() },
  { name: 'Saravanan', phone: '9159150663', opening_balance: 0.0, created_at: new Date() },
  { name: 'Saravanan Manager', phone: '8946014913', opening_balance: 0.0, created_at: new Date() },
  { name: 'Saravanan Mesthiri', phone: '9751834447', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Sathyam Construction',
    phone: '9841094166',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'SDF', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SDK', phone: '9751371706', opening_balance: 0.0, created_at: new Date() },
  { name: 'Seeni Driver', phone: '7667535780', opening_balance: 0.0, created_at: new Date() },
  { name: 'Seenivasan Eng', phone: '9092278533', opening_balance: 0.0, created_at: new Date() },
  { name: 'Seenivasan Ternary', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sekar Mesthiri', phone: '9366121416', opening_balance: 0.0, created_at: new Date() },
  { name: 'Senthil Tyre', phone: '9443425562', opening_balance: 0.0, created_at: new Date() },
  { name: 'Shakil Bhai', phone: '9043298793', opening_balance: 0.0, created_at: new Date() },
  { name: 'Shiva T', phone: '8883278420', opening_balance: 0.0, created_at: new Date() },
  { name: 'Shivaji', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Shivaji Theater', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sivakumar P', phone: '8248283917', opening_balance: 0.0, created_at: new Date() },
  { name: 'SJV Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sml Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SMLS Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SMT Lorry', phone: '9894920959', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sokkalingam Ri', phone: '9944226604', opening_balance: 0.0, created_at: new Date() },
  { name: 'SPT Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SR Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SRM Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'SRS Lorry', phone: '9344465787', opening_balance: 0.0, created_at: new Date() },
  { name: 'SSS Construction', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Subramani (GSK)', phone: '9003370713', opening_balance: 0.0, created_at: new Date() },
  { name: 'Subramani Driver', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Suresh Driver', phone: '9655727874', opening_balance: 0.0, created_at: new Date() },
  { name: 'SVM Lorry', phone: '9786373636', opening_balance: 0.0, created_at: new Date() },
  { name: 'Tamil Selvan', phone: '9751834219', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thangavel Mesthiri', phone: '7639345100', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thimanur HB', phone: '9787106059', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thirumalai BUNK', phone: '9944342861', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thirumalai Vellakuttai', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thirupathi', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thulasi Mesthiri', phone: '6369309990', opening_balance: 0.0, created_at: new Date() },
  { name: 'TLG', phone: '6382806365', opening_balance: 0.0, created_at: new Date() },
  { name: 'Track Computer', phone: '9095714888', opening_balance: 0.0, created_at: new Date() },
  { name: 'Utham Cl Road', phone: '6381104504', opening_balance: 0.0, created_at: new Date() },
  { name: 'Uzhavan Agro', phone: '7200728886', opening_balance: 0.0, created_at: new Date() },
  { name: 'Vanitech', phone: '9443368704', opening_balance: 0.0, created_at: new Date() },
  { name: 'Varathan', phone: '9003763662', opening_balance: 0.0, created_at: new Date() },
  { name: 'VBS', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Velmani Driver', phone: '9486254337', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Velmurugan Mesthiri',
    phone: '9786565666',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Vijay HB', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Vijay Medical', phone: '9786133323', opening_balance: 0.0, created_at: new Date() },
  { name: 'VNK Lorry', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'VNM', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'VPS', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'VRM', phone: '9442664097', opening_balance: 0.0, created_at: new Date() },
  { name: 'VSL HB', phone: '6382697485', opening_balance: 0.0, created_at: new Date() },
  { name: 'Yalini Traders', phone: '6379511876', opening_balance: 0.0, created_at: new Date() },
  { name: 'Yogava Traders', phone: '6369984597', opening_balance: 0.0, created_at: new Date() },
  { name: 'Sekar', phone: '9443233913', opening_balance: 0.0, created_at: new Date() },
  { name: 'Thapresh', phone: '9361002337', opening_balance: 0.0, created_at: new Date() },
  { name: 'MR Steel', phone: '9585021931', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Devi Vengatachalam College',
    phone: '9807293999',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Balraman Mesthiri', phone: '9486254337', opening_balance: 0.0, created_at: new Date() },
  { name: 'Tirupathy', phone: '8072175358', opening_balance: 0.0, created_at: new Date() },
  {
    name: 'Islamiah Womens College',
    phone: '9894150004',
    opening_balance: 0.0,
    created_at: new Date(),
  },
  { name: 'Shoe Berry', phone: '8778101419', opening_balance: 0.0, created_at: new Date() },
  { name: 'SVS Automobile', phone: '9443552436', opening_balance: 0.0, created_at: new Date() },
  { name: 'Light House Bhai', phone: '9976523567', opening_balance: 0.0, created_at: new Date() },
  { name: 'Rathna Textiles', phone: '9245434275', opening_balance: 0.0, created_at: new Date() },
  { name: 'Rathana Textiles', phone: '9245434275', opening_balance: 0.0, created_at: new Date() },
  { name: 'Tirupathy Mesthiri', phone: '9943958642', opening_balance: 0.0, created_at: new Date() },
  { name: 'Annadurai Cont', phone: '8973550716', opening_balance: 0.0, created_at: new Date() },
  { name: 'Siva Fort', phone: '9751804646', opening_balance: 0.0, created_at: new Date() },
  { name: 'Paavedan', phone: '9843558405', opening_balance: 0.0, created_at: new Date() },
  { name: 'EB AD', phone: '7904636533', opening_balance: 0.0, created_at: new Date() },
  { name: 'Dasarathan', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Dhasarathan', phone: '8940307744', opening_balance: 0.0, created_at: new Date() },
  { name: 'Palani Welder', phone: '9047564695', opening_balance: 0.0, created_at: new Date() },
  { name: 'Mathubalan Driver', phone: '7010741414', opening_balance: 0.0, created_at: new Date() },
  { name: 'Palani AL', phone: '8637651843', opening_balance: 0.0, created_at: new Date() },
  { name: 'Selvam', phone: '9443203095', opening_balance: 0.0, created_at: new Date() },
  { name: 'Tanveer Eng', phone: '', opening_balance: 0.0, created_at: new Date() },
  { name: 'Tanveer Engg', phone: '7845613049', opening_balance: 0.0, created_at: new Date() },
  { name: 'Giri Govindharaj', phone: '9843336971', opening_balance: 0.0, created_at: new Date() },
  { name: 'Naveen Bunk', phone: '9843373358', opening_balance: 0.0, created_at: new Date() },
];

// Specify a unique field to prevent duplicates (using name as unique identifier)
export const uniqueField = 'name';
