// seed/party.js
export const collectionName = 'party';

// Seed data - converted from SQL format to MongoDB document format
export const seedData = [
  { name: 'ADS', phone: '9790029726', openingBalance: 0.0, createdAt: new Date() },
  { name: 'AGS', phone: '9894217717', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Akbar Kousar', phone: '9751066446', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Amir Bhai', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Anandhan Auditor', phone: '8489855689', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Anbu Alangayam', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Annamalayar Lorry', phone: '9443348605', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Annasamy Lorry', phone: '9626803399', openingBalance: 0.0, createdAt: new Date() },
  { name: 'ANU Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'APN', phone: '9655408325', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Apollo Traders', phone: '9443492925', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ashokan Jabrabath', phone: '7845651972', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Asif Bhai', phone: '9842325213', openingBalance: 0.0, createdAt: new Date() },
  { name: 'ATA', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'AVM Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'AVR Lorry', phone: '8098821310', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Babu Auto', phone: '9003810729', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Babu Mesthiri', phone: '9443872492', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Bangaru Cleaner', phone: '9442744676', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Bangaru Driver', phone: '9442744676', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Bath Auto', phone: '9003810729', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Bethapalliyamman Kovil',
    phone: '9943310139',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'BK Mani', phone: '9698869671', openingBalance: 0.0, createdAt: new Date() },
  { name: 'BKB Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'BKP Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'College Hostal', phone: '9894150004', openingBalance: 0.0, createdAt: new Date() },
  { name: 'College Principal', phone: '9486528846', openingBalance: 0.0, createdAt: new Date() },
  { name: 'CSK', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Dhashnamoorthy', phone: '9159654756', openingBalance: 0.0, createdAt: new Date() },
  { name: 'DKP Lorry', phone: '9789451911', openingBalance: 0.0, createdAt: new Date() },
  { name: 'DR Lorry', phone: '9786339076', openingBalance: 0.0, createdAt: new Date() },
  { name: 'DRS Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Elavarasan', phone: '9943644105', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Emrold Leather', phone: '9443353551', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Eniyavan Auto', phone: '9843719307', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Forest Babu', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Forest Office', phone: '9443541922', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ganesh Babu', phone: '8939908357', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ganesh Tracktor', phone: '8072258461', openingBalance: 0.0, createdAt: new Date() },
  { name: 'GBR Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Gokul Motors', phone: '8072946034', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Gopal Lorry', phone: '9790001768', openingBalance: 0.0, createdAt: new Date() },
  { name: 'GSK', phone: '9003370713', openingBalance: 0.0, createdAt: new Date() },
  { name: 'GSK Kumar', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'GSK Manager', phone: '9047469066', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Guna Manager', phone: '8489614965', openingBalance: 0.0, createdAt: new Date() },
  { name: 'GVM Lorry', phone: '9943657909', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Hari Ohm Balaji Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Herbal Garden', phone: '9943156731', openingBalance: 0.0, createdAt: new Date() },
  { name: 'HM Rafiq', phone: '9443490952', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ikbal Road Majid', phone: '9790306797', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Irshad Bhai', phone: '9443390157', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Islamiah College', phone: '9894150004', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Islamiah School', phone: '9894958145', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Jagadisan', phone: '9751545991', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Jamal Bhai', phone: '8220544004', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Janatha Patrai', phone: '9500919724', openingBalance: 0.0, createdAt: new Date() },
  { name: 'JKT', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'JNS', phone: '9443091305', openingBalance: 0.0, createdAt: new Date() },
  { name: 'JNS Lorry', phone: '9443091305', openingBalance: 0.0, createdAt: new Date() },
  { name: 'JPP', phone: '9787852862', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Juber Bhai', phone: '8925393141', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kalam School', phone: '9043344080', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kanagarj Mesthiri', phone: '9943924269', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kandavel Trackter', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kavi Soap', phone: '8220162433', openingBalance: 0.0, createdAt: new Date() },
  { name: 'KBR', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'KBR Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'KK Shoes', phone: '9597300488', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Krishna Lorry', phone: '9003875894', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Krishnamoorthy Mayilparai',
    phone: '9843172296',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  {
    name: 'Krishnamoorthy Mesthiri',
    phone: '9751436645',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'KSM Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kumar Driving School', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Kumaran Lorry', phone: '8110011838', openingBalance: 0.0, createdAt: new Date() },
  { name: 'KVS Lorry', phone: '9080851773', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Lakshmi Store', phone: '9443882405', openingBalance: 0.0, createdAt: new Date() },
  { name: 'LMK Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'LNV Lorry', phone: '9786044807', openingBalance: 0.0, createdAt: new Date() },
  { name: 'LSK Yelagiri', phone: '9789395555', openingBalance: 0.0, createdAt: new Date() },
  { name: 'LSS Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MA Lorry', phone: '9787471898', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mani Mesan', phone: '9787461683', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mani Meson', phone: '9585713174', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Manigandan Pudur', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mano Vellakuttai', phone: '9943626069', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Marapattu HB', phone: '9677790437', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Maruthamalai', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MBS Lorry', phone: '9944090662', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mel Nimmiyampattu Party', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MKB Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MKR', phone: '9626076801', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MKR Mahendiran', phone: '9600806696', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MKR Rajendiran', phone: '9894785661', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MLS Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MLS Lorry, Mullai', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mohan Mosic', phone: '', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Moorthi Jamunamathur',
    phone: '9751555945',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Moorthy JPT', phone: '9789602547', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MPM Lorry', phone: '9843352185', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MRT Lorry', phone: '8098978696', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MSS Lorry', phone: '9943676089', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mukthiyar Bhai', phone: '9994178380', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mullai Bunk, Marapattu', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Munisamy', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Munivel Poongulam', phone: '6380423002', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Murugan', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Murugesan Tractor', phone: '6369756856', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Narayana Mesthiri', phone: '9626919356', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Nashir Bhai', phone: '7010090516', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Naveed Traders', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Naveen Spare Parts', phone: '9655867032', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Nawaz Bhai', phone: '9543392196', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ns & Co', phone: '9443687211', openingBalance: 0.0, createdAt: new Date() },
  { name: 'NSH Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'O Mohanraj School', phone: '8825596789', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Ohm Muruga Construction',
    phone: '7904820993',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Palani Mesthiri', phone: '8754179172', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Palanimurugan Lorry',
    phone: '8870100327',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Parthiban Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Party', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Party 909', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Party 912', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Party Auto', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Party T', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Pattabi', phone: '9025088855', openingBalance: 0.0, createdAt: new Date() },
  { name: 'PBJ Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Periyapettai Iyer', phone: '9743955052', openingBalance: 0.0, createdAt: new Date() },
  { name: 'PKP', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'PMC Lorry', phone: '9902564857', openingBalance: 0.0, createdAt: new Date() },
  { name: 'PMS', phone: '9786715459', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Prime Engineers', phone: '9952942812', openingBalance: 0.0, createdAt: new Date() },
  { name: 'PRR', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ragavendra Electrical', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Ramesh Tracktor', phone: '9943673865', openingBalance: 0.0, createdAt: new Date() },
  { name: 'RKS', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'RMD Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sai Construction', phone: '9943872300', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sankar Konnampatti', phone: '9150652961', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sarathi VNB', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Saravana Cement', phone: '9751845554', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Saravanan', phone: '9159150663', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Saravanan Manager', phone: '8946014913', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Saravanan Mesthiri', phone: '9751834447', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Sathyam Construction',
    phone: '9841094166',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'SDF', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SDK', phone: '9751371706', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Seeni Driver', phone: '7667535780', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Seenivasan Eng', phone: '9092278533', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Seenivasan Ternary', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sekar Mesthiri', phone: '9366121416', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Senthil Tyre', phone: '9443425562', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Shakil Bhai', phone: '9043298793', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Shiva T', phone: '8883278420', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Shivaji', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Shivaji Theater', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sivakumar P', phone: '8248283917', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SJV Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sml Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SMLS Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SMT Lorry', phone: '9894920959', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sokkalingam Ri', phone: '9944226604', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SPT Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SR Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SRM Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SRS Lorry', phone: '9344465787', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SSS Construction', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Subramani (GSK)', phone: '9003370713', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Subramani Driver', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Suresh Driver', phone: '9655727874', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SVM Lorry', phone: '9786373636', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Tamil Selvan', phone: '9751834219', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thangavel Mesthiri', phone: '7639345100', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thimanur HB', phone: '9787106059', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thirumalai BUNK', phone: '9944342861', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thirumalai Vellakuttai', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thirupathi', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thulasi Mesthiri', phone: '6369309990', openingBalance: 0.0, createdAt: new Date() },
  { name: 'TLG', phone: '6382806365', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Track Computer', phone: '9095714888', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Utham Cl Road', phone: '6381104504', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Uzhavan Agro', phone: '7200728886', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Vanitech', phone: '9443368704', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Varathan', phone: '9003763662', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VBS', phone: '', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Velmurugan Mesthiri',
    phone: '9786565666',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Vijay HB', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Vijay Medical', phone: '9786133323', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VNK Lorry', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VNM', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VPS', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VRM', phone: '9442664097', openingBalance: 0.0, createdAt: new Date() },
  { name: 'VSL HB', phone: '6382697485', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Yalini Traders', phone: '6379511876', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Yogava Traders', phone: '6369984597', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Sekar', phone: '9443233913', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Thapresh', phone: '9361002337', openingBalance: 0.0, createdAt: new Date() },
  { name: 'MR Steel', phone: '9585021931', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Devi Vengatachalam College',
    phone: '9807293999',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Balraman Mesthiri', phone: '9486254337', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Tirupathy', phone: '8072175358', openingBalance: 0.0, createdAt: new Date() },
  {
    name: 'Islamiah Womens College',
    phone: '9894150004',
    openingBalance: 0.0,
    createdAt: new Date(),
  },
  { name: 'Shoe Berry', phone: '8778101419', openingBalance: 0.0, createdAt: new Date() },
  { name: 'SVS Automobile', phone: '9443552436', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Light House Bhai', phone: '9976523567', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Rathna Textiles', phone: '9245434275', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Rathana Textiles', phone: '9245434275', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Tirupathy Mesthiri', phone: '9943958642', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Annadurai Cont', phone: '8973550716', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Siva Fort', phone: '9751804646', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Paavedan', phone: '9843558405', openingBalance: 0.0, createdAt: new Date() },
  { name: 'EB AD', phone: '7904636533', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Dasarathan', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Dhasarathan', phone: '8940307744', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Palani Welder', phone: '9047564695', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Mathubalan Driver', phone: '7010741414', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Palani AL', phone: '8637651843', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Selvam', phone: '9443203095', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Tanveer Eng', phone: '', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Tanveer Engg', phone: '7845613049', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Giri Govindharaj', phone: '9843336971', openingBalance: 0.0, createdAt: new Date() },
  { name: 'Naveen Bunk', phone: '9843373358', openingBalance: 0.0, createdAt: new Date() },
];

// Specify a unique field to prevent duplicates (using name as unique identifier)
export const uniqueField = 'name';
