// seed/vehicle.js
export const collectionName = 'vehicle';

export const indexes = [
  // Composite unique index on short_number + full_number
  { spec: { short_number: 1, full_number: 1 }, options: { unique: true } },

  // Other indexes for performance
  { spec: { full_number: 1 } },
  { spec: { is_company_vehicle: 1 } },
  { spec: { short_number: 1, is_company_vehicle: 1 } },
];

// Specify which fields together form a unique combination
export const uniqueFields = ['short_number', 'full_number'];

// Optional: Define MongoDB schema validation
export const validationRules = {
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['short_number', 'is_company_vehicle'],
      properties: {
        full_number: {
          bsonType: ['string', 'null'],
          description: 'must be a string or null',
        },
        short_number: {
          bsonType: 'string',
          description: 'must be a string and is required',
        },
        is_company_vehicle: {
          bsonType: 'bool',
          description: 'must be a boolean and is required',
        },
        body_capacity: {
          bsonType: ['double', 'null'],
          minimum: 0,
          maximum: 100,
          description: 'must be a number between 0-100 or null',
        },
        created_at: {
          bsonType: ['date', 'null'],
          description: 'must be a date or null',
        },
      },
    },
  },
  level: 'strict',
  action: 'error',
};

// Seed data - converted from SQL format to MongoDB document format
export const seedData = [
  {
    full_number: null,
    short_number: '8961 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3111 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9761 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8982 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3652 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3874 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9553 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7277 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7299 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1465 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3303 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7320 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0196 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1566 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4971 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4844 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3533',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8915',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2682',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9020',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4082',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4312',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4459',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8313',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7277',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5773',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8858',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7197',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4080',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1896',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1875',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1874',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1868',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9752',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9199',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0901',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0540',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9586',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9506',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9397',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8879',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6280',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6235',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4442',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2662',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9617',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4977',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1211',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0474',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0473',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0472',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0470',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8383',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9250',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1930',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2118',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8592',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3818',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3301',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5080',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4307',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8873',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0254',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6876',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3384',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7979',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7799',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2233',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0532',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3693',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9408',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9671',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9627',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7999',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0508',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0477',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9130',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3535',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2777',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6413',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6039',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2640',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9569',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9495',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9721',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8244',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0653',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0803',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7214',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5852',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5070',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7575',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1941',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7561',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7909',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7489',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0146',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1463',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4132',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6930',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9542',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7171',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8222',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0156',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5621',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8309',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4497',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3127',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2517',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1431',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8172',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4348',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5177',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4419',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4201',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1917',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0132',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9037',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9245',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6897',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8201',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5351',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7011',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5799',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9177',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0871',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8320',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7948',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4399',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7727',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1910',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4037',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9248',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6942',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4772',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8637',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5127',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1998',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9368',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1244',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7077',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1063',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5847',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1543',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1453',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1568',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4820',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2100',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9091',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7059',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0325',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7288',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1400',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9657',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4043',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8475',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3934',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9576',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4638',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7187',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2639',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4033',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8097',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1996',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6300',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0864',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5930',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5207',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1877',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5707',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3953',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6991',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7404',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2026',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2712',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8315',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7240',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1206',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6564',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1703',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7547',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1598',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6259',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6971',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1149',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5099',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2847',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0664',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3369',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7607',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0020',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6102',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9874',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3753',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6753',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9481',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0797',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3627',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5833',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0365',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4797',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5825',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3290',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6124',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8556',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9034',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7821',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1424',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7662',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9340',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3938',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4781',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8212',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5611',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6463',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2799',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7426',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9358',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0936',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6085',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0335',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6664',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2823',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6105',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6325',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4909',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0781',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0258',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2917',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9266',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5691',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6107',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8345',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4137',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9743',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7000',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4659',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5200',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5321',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9940',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3348',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1882',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3822',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1891',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0031',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4424',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3921',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2181',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8314',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5392',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7025',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9616',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2363',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2703',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4614',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3691',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5880',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3103',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2217',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8278',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7247',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5050',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4767',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3243',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3834',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8542',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7473',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9639',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8749',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1940',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9748',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2717',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4699',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0388',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9610',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4961 K',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7029',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0191',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: 'Auto',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: 'Tractor',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: 'Lorry',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0556 K',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0768',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1849',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0386',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8956',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5391',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2371',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9295',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5153',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4871',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4179',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9117',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0837',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4520',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6770',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6228',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8912',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0391',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3892',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8043',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7327',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7686',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5212',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6212',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2525',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4545',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6743',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9897',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6205',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7558',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7952',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3769',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3291',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7443',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1144',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6873',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9249',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3412',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1188',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0200',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9596',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3327',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6982',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4007',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0806',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3319',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3584',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8032',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9861',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3799',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3669',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4801',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8446',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8012',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6585',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4383',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4085',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1950',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4412',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9312',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6332',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2928',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1147',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5427',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2978',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8163',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4361',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5826',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2683',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4059',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7471',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0643',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3675',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7068',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1796',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1033',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1148',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0591',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5738',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8892',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3374',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6887',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8010',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2327',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0133',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6193',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2266',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4945',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4549',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2299',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5044',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8150',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3404',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2889',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1118',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0199',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7201',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5214',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1461',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4176',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4136',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0707',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8082',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0441',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1633',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: 'New',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4879',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2061',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6125',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1020',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9669',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6909',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1219',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0500',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0688',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9804',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2507',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7993',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5013',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4185',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4849',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2372',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6757',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6828',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4847',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9243',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6446',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4606',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2459',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7458',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5953',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3674',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5314',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8391',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6894',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2436',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2851',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2935',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8577',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0974',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6009',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6703',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2130',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3868',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5154',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0482',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1662',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3172',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9246',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2336',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7063',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2352',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4816',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1044',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8996',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3534',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9185',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3685',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2283',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2792',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8584',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8141',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2782',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4109',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6197',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6813',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3963',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7689',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0484',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8925',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7061',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2119',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4019',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7054',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0945',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6793',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7104',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8070',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2491',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2263',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4197',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4091',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1210',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0384',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: ' 3874',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7232',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4315',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4491',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7500',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3143',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2264',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6684',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2761',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8650',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1040',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5469',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1481',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0941',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9319',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7875',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0558',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7714',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0833',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3887',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3487',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '4461',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7134',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1499',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5131',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2412',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0488',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2479',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9477',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8740',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7619',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8932',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9699',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0734',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5101',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2787',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1083',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3830',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5052 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5067 G',
    is_company_vehicle: true,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '6091',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3505',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3485',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '8422',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3448',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7228',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5836',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5216',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1819',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '2072',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '3943',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '7722',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '1349',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9901',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '9241',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '0363',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
  {
    full_number: null,
    short_number: '5455',
    is_company_vehicle: false,
    body_capacity: null,
    created_at: new Date(),
  },
];
