// seed/vehicle.js
export const collectionName = 'vehicle';

// Seed data - converted from SQL format to MongoDB document format
export const seedData = [
  {
    fullNumber: null,
    shortNumber: '8961 G',
    isCompanyVehicle: true,
    bodyCapacity: [0.5, 0.25],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3111 G',
    isCompanyVehicle: true,
    bodyCapacity: [1, 0.75, 0.5],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9761 G',
    isCompanyVehicle: true,
    bodyCapacity: [1, 0.75, 0.5],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8982 G',
    isCompanyVehicle: true,
    bodyCapacity: [2, 1.5],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3652 G',
    isCompanyVehicle: true,
    bodyCapacity: [2, 1.5, 1],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3874 G',
    isCompanyVehicle: true,
    bodyCapacity: [2, 1.5, 1],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9553 G',
    isCompanyVehicle: true,
    bodyCapacity: [2, 1.5, 1],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7277 G',
    isCompanyVehicle: true,
    bodyCapacity: [4, 3],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7299 G',
    isCompanyVehicle: true,
    bodyCapacity: [4, 3],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1465 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3303 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7320 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0196 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1566 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4971 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4844 G',
    isCompanyVehicle: true,
    bodyCapacity: [6],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3533',
    isCompanyVehicle: false,
    bodyCapacity: [1, 0.5],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8915',
    isCompanyVehicle: false,
    bodyCapacity: [1, 0.5],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2682',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9020',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4082',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4312',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4459',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8313',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7277',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5773',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8858',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7197',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4080',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1896',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1875',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1874',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1868',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9752',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9199',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0901',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0540',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9586',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9506',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9397',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8879',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6280',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6235',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4442',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2662',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9617',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4977',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1211',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0474',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0473',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0472',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0470',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8383',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9250',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1930',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2118',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8592',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3818',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3301',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5080',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4307',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8873',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0254',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6876',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3384',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7979',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7799',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2233',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0532',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3693',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9408',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9671',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9627',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7999',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0508',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0477',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9130',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3535',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2777',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6413',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6039',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2640',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9569',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9495',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9721',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8244',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0653',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0803',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7214',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5852',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5070',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7575',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1941',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7561',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7909',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7489',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0146',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1463',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4132',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6930',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9542',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7171',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8222',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0156',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5621',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8309',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4497',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3127',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2517',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1431',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8172',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4348',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5177',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4419',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4201',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1917',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0132',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9037',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9245',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6897',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8201',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5351',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7011',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5799',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9177',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0871',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8320',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7948',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4399',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7727',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1910',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4037',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9248',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6942',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4772',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8637',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5127',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1998',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9368',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1244',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7077',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1063',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5847',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1543',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1453',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1568',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4820',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2100',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9091',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7059',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0325',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7288',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1400',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9657',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4043',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8475',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3934',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9576',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4638',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7187',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2639',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4033',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8097',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1996',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6300',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0864',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5930',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5207',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1877',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5707',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3953',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6991',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7404',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2026',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2712',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8315',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7240',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1206',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6564',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1703',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7547',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1598',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6259',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6971',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1149',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5099',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2847',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0664',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3369',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7607',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0020',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6102',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9874',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3753',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6753',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9481',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0797',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3627',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5833',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0365',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4797',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5825',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3290',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6124',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8556',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9034',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7821',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1424',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7662',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9340',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3938',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4781',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8212',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5611',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6463',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2799',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7426',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9358',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0936',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6085',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0335',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6664',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2823',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6105',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6325',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4909',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0781',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0258',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2917',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9266',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5691',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6107',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8345',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4137',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9743',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7000',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4659',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5200',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5321',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9940',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3348',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1882',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3822',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1891',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0031',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4424',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3921',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2181',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8314',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5392',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7025',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9616',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2363',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2703',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4614',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3691',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5880',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3103',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2217',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8278',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7247',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5050',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4767',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3243',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3834',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8542',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7473',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9639',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8749',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1940',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9748',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2717',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4699',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0388',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9610',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4961 K',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7029',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0191',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: 'Auto',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: 'Tractor',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: 'Lorry',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0556 K',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0768',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1849',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0386',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8956',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5391',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2371',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9295',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5153',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4871',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4179',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9117',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0837',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4520',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6770',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6228',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8912',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0391',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3892',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8043',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7327',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7686',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5212',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6212',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2525',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4545',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6743',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9897',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6205',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7558',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7952',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3769',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3291',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7443',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1144',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6873',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9249',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3412',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1188',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0200',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9596',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3327',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6982',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4007',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0806',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3319',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3584',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8032',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9861',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3799',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3669',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4801',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8446',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8012',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6585',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4383',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4085',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1950',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4412',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9312',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6332',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2928',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1147',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5427',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2978',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8163',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4361',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5826',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2683',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4059',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7471',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0643',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3675',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7068',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1796',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1033',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1148',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0591',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5738',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8892',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3374',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6887',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8010',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2327',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0133',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6193',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2266',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4945',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4549',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2299',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5044',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8150',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3404',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2889',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1118',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0199',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7201',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5214',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1461',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4176',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4136',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0707',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8082',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0441',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1633',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: 'New',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4879',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2061',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6125',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1020',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9669',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6909',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1219',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0500',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0688',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9804',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2507',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7993',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5013',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4185',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4849',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2372',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6757',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6828',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4847',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9243',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6446',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4606',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2459',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7458',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5953',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3674',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5314',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8391',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6894',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2436',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2851',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2935',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8577',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0974',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6009',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6703',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2130',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3868',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5154',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0482',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1662',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3172',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9246',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2336',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7063',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2352',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4816',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1044',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8996',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3534',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9185',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3685',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2283',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2792',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8584',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8141',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2782',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4109',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6197',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6813',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3963',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7689',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0484',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8925',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7061',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2119',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4019',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7054',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0945',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6793',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7104',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8070',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2491',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2263',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4197',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4091',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1210',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0384',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: ' 3874',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7232',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4315',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4491',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7500',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3143',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2264',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6684',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2761',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8650',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1040',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5469',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1481',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0941',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9319',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7875',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0558',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7714',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0833',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3887',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3487',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '4461',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7134',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1499',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5131',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2412',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0488',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2479',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9477',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8740',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7619',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8932',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9699',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0734',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5101',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2787',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1083',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3830',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5052 G',
    isCompanyVehicle: true,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5067 G',
    isCompanyVehicle: true,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '6091',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3505',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3485',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '8422',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3448',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7228',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5836',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5216',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1819',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '2072',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '3943',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '7722',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '1349',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9901',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '9241',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '0363',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
  {
    fullNumber: null,
    shortNumber: '5455',
    isCompanyVehicle: false,
    bodyCapacity: [],
    createdAt: new Date(),
  },
];
