import { applyProjection } from '../base/BaseMode';

export default function PartyStatement(
  {
    id = null,
    partyStatementNumber = null,
    partyName = null,
    address = null,
    phone = null,
    item = null,
    totalQty = 0,
    paymentAt = null,
    amountType = 'COD',
    amount = 0,
    advance = 0,
    discount = 0,
    sign = false,
    isOwnerPartyStatement = false,
    tracktorOnly = false,
    deliveredQty = 0,
    notes = '',
    status = 'New',
    deliverySheetVerified = 0,
    createdAt = null,
    updatedAt = null,
  } = {},
  projection = {},
) {
  const allFields = {
    id,
    partyStatementNumber,
    partyName,
    address,
    phone,
    item,
    totalQty,
    paymentAt,
    amountType,
    amount,
    advance,
    discount,
    sign,
    isOwnerPartyStatement,
    tracktorOnly,
    deliveredQty,
    notes,
    status,
    deliverySheetVerified,
    createdAt,
    updatedAt,
    balance: amount - advance - discount,
    balanceQty: totalQty - deliveredQty,
  };
  return applyProjection(allFields, projection);
}
