import { applyProjection } from '../base/BaseMode';

export default function Address(
  {
    id = null,
    orderNumber = null,
    partyName = null,
    address = null,
    phone = null,
    item = null,
    totalQty = 0,
    paymentAt = null,
    amountType = 'Credit',
    amount = 0,
    advance = 0,
    discount = 0,
    sign = false,
    isOwnerOrder = false,
    tracktorOnly = false,
    deliveredQty = 0,
    notes = '',
    status = 'New',
    deliverySheetVerified = 0,
    createdAt = null,
    updatedAt = null,
    balance = amount - advance - discount,
    balanceQty = totalQty - deliveredQty,
  } = {},
  projection = {},
) {
  const allFields = {
    id,
    orderNumber,
    partyName,
    address,
    phone,
    item,
    totalQty,
    paymentAt,
    amountType,
    amount,
    advance,
    discount,
    sign,
    isOwnerOrder,
    tracktorOnly,
    deliveredQty,
    notes,
    status,
    deliverySheetVerified,
    createdAt,
    updatedAt,
    balance,
    balanceQty,
  };
  return applyProjection(allFields, projection);
}
